version: "3.9"
services:
  php:
    build: ./infra/php
    volumes:
      - ./backend:/src
    # ports:
    #   - 8081:8081
    #   - 3000:3000
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  # db:
  #   image: mariadb
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: database
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: pass
  #     TZ: Asia/Tokyo
  #   volumes:
  #     - db-data:/var/lib/mysql
  #   ports:
  #     - 13306:3306
